- docs/source/installation.rst
The documentation was missing a dependency for urwidtrees in the installation manual.
> altered installation documentation, that urwidtrees is a dependency

- extra/alot.desktop
This file can enable desktop environments to use alot for mailto links and
display it in application menus.  It also enables alot to be used with
xdg-email(1) and friends.
> Add a .desktop file.

- alot/__init__.py
Setuptools gave an error message and asked to conform to PEP440.
https://www.python.org/dev/peps/pep-0440/#developmental-releases
> Fix version number for development.

- alot/widgets/search.py
I could not get alot to start, and as a new user, I was a little bit frustrated.
I was getting the following backtrace on start:
````python
Traceback (most recent call last):
File "/usr/bin/alot", line 20, in <module>
main()
File "/usr/share/alot/alot/init.py", line 186, in main
UI(dbman, cmdstring)
File "/usr/share/alot/alot/ui.py", line 87, in __init__
self.mainloop.run()
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
self._run()
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
self.event_loop.run()
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1200, in wrapper
rval = f(*args,**kargs)
File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1159, in _twisted_idle_callback
callback()
File …
```
> Do not crash when emails' date is malformated.

- alot/addressbook/__init__.py
The name of the referenced class was changed in
637b679003b353d2630fed8ca942f3ab522e68b5.
> Fix docstring for alot.addressbook.AddressBook.

- alot/ui.py
- docs/source/usage/synopsis.rst
Small change to add a signal handler to UI that refreshes the current refreshes the current buffer when the program receives the SIGUSR1 signal. Tested on my system for about a month now and I have seen no problems. This is used to notify alot from my mail downloader to refresh the mail view.
> refresh current buffer on SIGUSR1

- alot/ui.py
Hello,
this patch bind the SIGINT (C-c) signal to an exit command, 
that way is you configure the 'bug_on_exit' flag you can confirm before quitting,
if you don't you still get a cleaner way for quitting due to the ExitCommand().
> Add signal for SIGINT callback ExitCommand

- alot/widgets/globals.py
I have found it hard to get to using Esc to cancel commands, and as far as I can tell that keybinding is baked-in and cannot be changed in the configuration file.  Thus I have created a patch that allows "ctrl-g" to be used  in addition to Esc (for cancelling commands) in order to allow it to be more friendly to those who have emacs keybindings built into their muscle memory.
> add ctrl-g keybinding to cancel prompt 

- alot/ui.py
Refreshing non-search buffers (eg the thread view) can have undesired
effects. This defensively only refreshes when the search
buffer is visible. (fixes #871)
Signed-off-by: Dimitrios Semitsoglou-Tsiapos <kmhzsem@gmx.com>
> ui: Only update via SIGINT1 when in search buffer

- alot/widgets/search.py
- docs/source/generate_configs.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Use `is` or `is not` to compare with `None`](https://www.quantifiedcode.com/app/issue_class/3IY8CZ0v)
Issue details: [https://www.quantifiedcode.com/app/project/gh:pazz:alot?groups=code_patterns/%3A3IY8CZ0v](https://www.quantifiedcode.com/app/project/gh:pazz:alot?groups=code_patterns/%3A3IY8CZ0v)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)
> Fix "Use `is` or `is not` to compare with `None`" issue

- alot/db/envelope.py
The substitution of the sequence `\t` (backslash followed by lowercase t, not tab) by four spaces when constructing a message alters the message contents (and makes no sense).
> Removed incorrect backslash-t substitution in envelope.

- alot/commands/thread.py
- alot/db/utils.py
When decoding the message, use the mailcap field specified for command
lookup.
> Allow specifing the mailcap field key for `pipeto`

- docs/source/api/settings.rst
Ran into this trying to update the AUR package for alot to 0.4:
https://aur.archlinux.org/packages/alot
Building the docs was failing.
Hopefully this can be squeezed into a fixup release? would prefer not to have to keep a backported version of this patch in the aur package.
> docs: fix incorrect module/class names

- alot/commands/globals.py
- alot/commands/search.py
- docs/Makefile
- docs/source/configuration/accounts_table
- docs/source/configuration/alotrc_table
- docs/source/generate_commands.py
- docs/source/generate_configs.py
- docs/source/installation.rst
- docs/source/usage/modes/envelope.rst
- docs/source/usage/modes/global.rst
- docs/source/usage/modes/search.rst
- docs/source/usage/modes/thread.rst
Sorry there where quite some things I overlooked in #912.
> Some more fixes for building docs

- .travis.yml
For starters only the auto generated part of the docs is regenerated in order
to check that the last author did regenerate and commit them.
Some dependencies of alot are mocked to speed up installation.  Especially
notmuch would need to be build manually as the version available on travis is
to old.
This is a follow up PR for #886.  A proof of concept about the behaviour of this test in case of failure can be seen in the branch [mini-travis-proof-of-concept](https://travis-ci.org/lucc/alot/branches).  This branch should pass.
In order to start using the travis.ci @pazz has to log in at https://travis.ci (with your github account) and set things up (not hard I did it some time ago for my fork but don't remember the exact steps).
> Start using travis.ci to check auto generated docs

- .travis.yml
Two jobs are set up to run on travis.  Both run on Ubuntu trusty (14.04) and
python2.7.  One checks and builds the docs and the other is set up to run the
test suite (currently only a small config file is used to start and quit alot
again, much like `vim -c quit`).
The longer and more complicated shell scripts are still kept in the travis
file (with yaml multi line strings).  They get the shell option `set -e` to
get the "short circuit" behaviour otherwise present with single statements
(also known from make files) to fail the whole job as soon as any single line
fails.
Currently the tests are run in a full VM as we need sudo to manually build a
new enough version of notmuch.  This can be changed when this PR is resolved:
https://github.com/travis-ci/apt-package-whitelist/issues/3895 …
> Set up several jobs to build docs and run tests in parallel

- alot/commands/envelope.py
- alot/commands/globals.py
- alot/db/message.py
- alot/helper.py
This little series replaces most uses of open() that are not as a context manager (using the `with` statement) with context manager uses. Using open as a context manager has a number of advantages, it makes visual inspection of correctness easier, it ensures that the file is closed and the fd is released (even if an exception is closed which would otherwise require a try/finally construct), and it uses one line less code than `f = open(...); f.write(...); f.close()`.
> Use open() as a context manager

- README.md
Per @lucc's comments in #923:
> The first few lines start to look patched together more and more. Maybe we can find a way to say
> things in a nicer looking way or we don't say everything at the top.
>
> But that can all be done in another PR. The badges are good and seem to point to the right place.
IMO footnote links make the source nicer to look at.
> Use footnote-links to clean up badges

- alot/settings/manager.py
Configobj's string interpolation feature does not work as expected in
account sections of alot configuration files.
The reason is that interpolation is done in ConfigObj.__getitem__
which alot does not use directly for account sections.
This patch causes all values to be read via ConfigObj.__getitem__
explicitly.
> fix interpolation in config files #902.

- alot/account.py
- alot/completion.py
- alot/settings/manager.py
- alot/ui.py
- alot/widgets/search.py
Fix some comments by quantifycode.  The other potential @staticmethods that QC reports are overwriting a super class method or are being overwritten in a subclass.  I didn't want to change the signature for those because some of the classes in the hierarchy might use the self parameter and then the signatures would differ.
> [QC] Turn methods with no `self` usage into staticmethods

- alot/db/message.py
- alot/helper.py
The safely_get helper is just a wrapper around try/except, and is used
twice in the whole code base, in the same function. It really doesn't
even end up saving code because to get around line wrapping a lambda is
assigned (which is not the greatest style wise), it ends up saving one
line of code when it's called, and the function itself is 16 lines long.
> Drop little used helper

- .travis.yml
Travis advises to prefer them and they start up much quicker compared to full
VMs.
This is now possible because
https://github.com/travis-ci/apt-package-whitelist/issues/3895 has been
resolved.
> Switch to container infrastructure on travis

- .travis.yml
This saves having to rebuild the pip packages that require building (like twisted) every time a job is run. This can save a bit of time in travis.
> Cache pip packages

- alot/buffers.py
- alot/commands/envelope.py
- alot/commands/globals.py
- alot/commands/search.py
- alot/commands/thread.py
- alot/commands/utils.py
- alot/db/attachment.py
- alot/db/envelope.py
- alot/db/message.py
- alot/db/utils.py
- alot/settings/theme.py
- alot/ui.py
- alot/widgets/utils.py
- docs/source/usage/modes/global.rst
- docs/source/usage/modes/search.rst
The majority of the changes in this series are whitespace related, and after this series pylint's complaints are down basically to missing docstrings a few other small things here and there. However, this series also contains a few other cleanups and optimizations, including the use of more iterators and fewer (intermediate) concrete objects, not calling dunder methods directly when not necessary, removing useless calls, renaming non-PEP8 variables, and adding TODO's for future cleanups and optimizations (mostly those that are invasive enough that I didn't feel comfortable implementing without unittests.
There are two refactors in here as well, one replaces the `__cmp__` protocol with the rich comparison protocol (`__eq__`, `__lt__`, etc). This is both a performance optimization and is …
> Even more cleanups

- .travis.yml
I did not find a setting to force every master branch build to send notifications. (maybe I missed something: https://docs.travis-ci.com/user/notifications/#IRC-notification) Is that still acceptable?
If we want we can also shorten the message that is send.
> Remove some irc notifications by travis

- alot/__main__.py
- docs/source/usage/synopsis.rst
As discussed in #942.
The command line interface is copied as directly as possible.  But at least the help output is formatted differently.  We still have to test this a litte bit to find out if I did not mess up some corner case with optional subcommands or some defaults for options.
I have some more ideas how to improve this and will try to add some more commits soon.  I will take care not to rebase so you can already have a look at what I put up already.
> Replace twisted command line parsing with argparse

- alot/buffers.py
- alot/commands/globals.py
One of the differences between map/filter and a comprehension is what
happens with None. For map and filter passing None as the function will
be treated as an identity function (equivalent to lambda x: x), for
comprehensions however, this will raise an exception (calling NoneType).
The fix is rather simple, instead of making the default of filtfun None,
make it an identity function. I've used lambda x: x since it's easy,
although defining an identity function in a utility library might be
preferable since lambdas are slower than normal functions.
Fixes #958
> Replace None passed to comprehensions with identity function

- alot/commands/envelope.py
- alot/commands/globals.py
- alot/commands/utils.py
If you activate encrypt on the envelop mode or you reply to an encrypted email by default only addresses in the To header are used to encrypt to, CC and BCC are not taking into account.
I'm solving this issue and also removing duplication of code.
> Encrypt for the CC and Bcc addresses too

- alot/commands/globals.py
This is a bug, though apparently no one has run into it yet. Found
through inspection.
> alot/commands/globals: fix typo

- alot/completion.py
The change this is partially reverting removed a variable assignment
that was actually needed.
Fixes #962
> alot/completion: revert premature optimization

- alot/defaults/alot.rc.spec
- alot/ui.py
- docs/source/configuration/alotrc_table
Enabling mouse support disables the possibility to select text using the mouse in the terminal window. This commit adds a setting, `handle_mouse`, that can be used to turn off mouse support which restores this behaviour.
Setting `handle_mouse = False` in the config file disables mouse support in `alot`. The default value is `True` as not to conflict with the previous commit that enabled mouse support.
*Updated*: Making this a PR for the mouse setting only. Also, holding `<shift>` seems to be a workaround for selecting text in a terminal that is running a program tracking the mouse.
> Settings for enabling mouse

- alot/helper.py
While the reality is that most alot users probably have glibc as their C
library and can therefore rely on %P, it is possible that there are
users or potential users who run a *BSD or other unix-like OS. This
leaves only non-GNU extensions, though some of the extensions are
specified in later POSIX, unix or C specifications.
> helper: Don't rely on GNU extensions for strftime

- .travis.yml
This will speed up the builds of notmuch, saving about 40 seconds of
time in travis.
> travis: Add ccache

- docs/source/configuration/contacts_completion.rst
The old regex that was suggested to capture addresses for completion from the
command `notmuch address` was bogus.  The json output format is much more
predictable.
Reported in #990.
> Suggest `notmuch address --format=json` in the docs

- alot/ui.py
This ports the same handling used in UI.apply_commandline to
UI.apply_command. This means that raising a CommandCanceled exception
trhough UI.apply_command will end up with a notification instead of a
stacktrace.
Fixes #965
> alot/ui: Handle Exceptions in UI.apply_command callbacks

- alot/commands/thread.py
This is just relaying the patch proposed in #818. related: #874.
`make_unique` should at least be documented properly, maybe made into a classmethod.
The docstring of `clear_my_address` need to be changed.
> Make addresses in To header unique when group replying 

- .travis.yml
This forces travis to install sphinx 1.5.1 which doesn't display the
warnings 1.5.2 does. This is not a proper solution, but a work around so
that the docs test works and remains useful. We still need to implement
a proper fix.
I am not marking this as a fix for the problem, we need to figure out whether we're doing something wrong, or whether this is a bug in sphinx, and address that accordingly.
> travis: work around sphinx-1.5.2 problem

- alot/commands/globals.py
- alot/commands/thread.py
- alot/completion.py
- tests/commands/thread_test.py
- tests/completion_test.py
There are some fine corner cases when generating a TO header from an address book.  Characters like `,'"` might need special treatment.  I opend this PR early (the code is not yet finished) in order to discuss some of the things with you.
Related: #990, #889
Points to check, discuss and decide:
At the moment I just wrote some tests to show you what I think are the cases we have to take care of.
> [RFC] Fix addressbook completion

- MANIFEST.in
We really don't need to distribute these (and no one wants them anyway),
so don't.
> Don't package tests

- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
As discussed elsewhere, handling the mouse was not done before, and
breaks work flows that include using the mouse for other things
(middle-clock paste). This only changes the default option to False.
> Default to not handling mouse

- alot/helper.py
- tests/helper_test.py
Technically a kilobyte (and it's derivatives like megabytes and
gigabytes) are defined as powers of 1000, while a kibibyte (and it's
derivatives like mibibytes and gibibytes) are defined as powers of 1024.
This patch fixes incorrect language and formatting in the humanize_size
function which defined a kilobyte as 1024.
See this wikipedia article for more information:
https://en.wikipedia.org/wiki/Kibibyte
> helper: Use kibi and mibibytes instead of kilo and megabytes

- alot/helper.py
- alot/widgets/globals.py
- alot/widgets/search.py
- alot/widgets/thread.py
- tests/widgets/globals_test.py
These two patches replace our remaining uses of `cmp` with built in rich comparisons. This should both optimize building the tag widgets (the final implementation takes < 30%) as long as the cmp implementation in my tests, though it should be noted there will be some additional cost to calling a method. This is also necessary for python 3, which doesn't have cmp.
This is the test script I used to verify the speed of the optimizations, in case anyone is interested:
```python
import functools
import timeit
def cmp_(a, b):
if min(len(a), len(b)) == 1 and max(len(a), len(b)) > 1:
return cmp(len(a), len(b))
return None
def orig(a, b):
a = len(a)
b = len(b)
if min(a, b) == 1 and max(a, b) > 1:
return a < b
return None
def orig2(a, b):
if min(len(a), len(b)) == 1 and max(len(a), len(b)) > 1: …
```
> Remove remaining uses of cmp

- alot/db/utils.py
Message doesn't have an iterkeys method, just a keys method.
> alot/db/utils: Revert use of iterkeys on Message

- tests/commands/envelope_tests.py
- tests/commands/init_test.py
- tests/commands/thread_test.py
- tests/completion_test.py
- tests/utils/argparse_test.py
- tests/utils/configobj_test.py
- tests/widgets/globals_test.py
There are a number of things pylint warns on that absolutely make sense
to fix in production code, but for unittests they either don't matter
(like naming variables "foo"), can't be fixed (TestCase methods that
don't use self because they use a mock assert), or the descriptive names
violate PEP8. These are annoying and create noise, so tell pylint to
ignore them.
> tests: Instruct pylint to ignore a large swath of warnings

- MANIFEST.in
- setup.py
* Include the tests in the sdist
* Don't install the test packages if present when running setup.py install.
This way installing correctly omits the tests/ subdirectory when installing from a git checkout -- previously this would install a package called "tests" as well. Furthermore, the tests are now included in the sdist, as they should be.
I was notified of the git checkout issue because I'm still using github's tarballs for the AUR package, and one of them was getting file conflicts (presumably with some other package making the same mistake, but I haven't heard back from them).
> Fix the packaging of tests

- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
It currently lists "terminal_command" in relation to "editor_spawn" but
the config option is actually "terminal_cmd".
> alot.rc.spec: Fix typo in documentation

- alot/defaults/alot.rc.spec
- alot/widgets/thread.py
- docs/source/configuration/alotrc_table
This introduces a new config option 'thread_focus_linewise',
(defaults to True), which determines if the message texts are
split into individually focussable lines in thread mode.
fixes #645
> optional linewise focussing in thread mode

- alot/buffers.py
- alot/walker.py
- alot/widgets/globals.py
There are some more in the code but I did not know which belong to some urwid interface that we implement and which could be removed.
If you agree I would say we should note which of our methods overwrite/implement some library interface in the docstring of the method. (Another job on the incremental TODO list.)
> Remove Java style getters

- alot/buffers.py
- alot/walker.py
I only noticed after the PR was merged that it seems to introduce a bug.  If I open any buffer I get the error message `No focus_position, ListBox is empty`.  If I revert these two commits the error is gone.  I assume that I deleted some of the interface of urwid that we need to implement and I was sloppy enough to not notice.
I am very sorry for the noise and inconvenience (at least it seems that nobody has used the code yet or at least nobody has reported it).  Please test the bug in master and the fix in this PR before you approve this PR.
> Revert parts of #1039

- .travis.yml
- docs/source/usage/index.rst
It turns out that commands was included in the toctree twice, which
caused warnings which we treat as errors in CI.
Fixes #994
> docs: Fix sphinx warnings (and build) on sphinx > 1.5.1

- tests/helper_test.py
Instead use %p, which differs only in the case of the am/pm.
Fixes #1048
> tests/helper_test.py: Don't use GNU %P, which breaks non glibc platforms

- docs/source/api/settings.rst
See __main__.py around line 35.
> Indicate usage of notmuch config file correctly

- docs/source/configuration/config_options.rst
This reference doesn't seem to actually be referenced anywhere, not even in the commit that added it.
> docs: Remove spurious reference _account in config_options

- alot/completion.py
- alot/utils/cached_property.py
via cached properties.
This should help with #1064 and is generally a good idea because most of the time, only specific sub-completer will be in use and so there is no need to instantiate all of them upfront.
The decorator used comes from the [werkzeug](https://github.com/pallets/werkzeug/blob/10b4b8b6918a83712170fdaabd3ec61cf07f23ff/werkzeug/utils.py#L35) toolkit, which is avoided as a dependency here.
> conservative lookup of sub-completers

- alot/commands/thread.py
- alot/crypto.py
- alot/db/utils.py
- alot/helper.py
- tests/addressbook/init_test.py
- tests/commands/thread_test.py
- tests/crypto_test.py
- tests/db/utils_test.py
I generated a coverage report with
```sh
coverage2 run setup.py test
coverage2 html --include=alot/'*'
xdg-open htmlcov/index.html
```
and picked some easy things that where not yet covered.
Now I have a question about the last test in the last commit.  It fails for me but I don't think that is consistent so I assume it is a bug.  What do you think about it?  And what is the intended behaviour for alot.commands.thread.determine_sender anyway?
> Add some tests

- alot/addressbook/__init__.py
- alot/addressbook/external.py
- tests/addressbook/external_test.py
- tests/settings/theme_test.py
- tests/settings/utils_test.py
These are some test cases I had lying around.  The test cases where constructed by looking at the code and executing it so find out what the results should be.
The last commit is a rather incomplete test as it only checks some error conditions.
38a2395b adds annotations to the source code in order to exclude some code from coverage reports by [coverage](http://nedbatchelder.com/code/coverage/).  They work analogous to the pylint comments we already have.  I hope it is acceptable that I just add something that might be specific to that tool even though we do not (yet?) officially use it.
> Some misc tests

- alot/helper.py
The spec is very clear here:
(2)  An appropriate Content-Transfer-Encoding is then applied; see
section 3.  In particular, line endings in the encoded data
MUST use the canonical <CR><LF> sequence where appropriate
(note that the canonical line ending may or may not be present
on the last line of encoded data and MUST NOT be included in
the signature if absent).
That very last MUST NOT is what's important here, we shouldn't be adding
newlines if they weren't there to begin with. Because we do it causes
signed blobs that have newlines to be invalid since we've changed the
substance of the signed code.
> helper: Do not add a newline to the end of a signed section

- alot/db/utils.py
- tests/crypto_test.py
- tests/db/utils_test.py
- tests/utilities.py
Currently if a signature name has a non-ascii unicode character in it,
the thread will fail to load because a UnicodeEncodeError. This patch
fixes that by converting the str into unicode.
> db/utils: Support unicode in signatures

- alot/commands/envelope.py
- alot/commands/utils.py
- alot/settings/errors.py
- alot/settings/manager.py
- tests/settings/manager_test.py
If there isn't a key provided as an argument to sign or togglesign, fall
back to using the account of the sending address to determine the key,
otherwise the message will be marked as "to sign", but won't actually be
signed. This is the same type of logic used for sign_by_default.
> commands/envelope: Fall back to account for signing key

- alot/defaults/theme.spec
- docs/source/configuration/theming.rst
... which displays a prefix of the msg contents. I forgot to list this
feature in the docs.
closes #1068
> docs: mention 'content' part in threadline theming

- .travis.yml
Generate a coverage report and upload it to codacy.com as discussed in #1087.
@pazz as said in https://github.com/pazz/alot/issues/1087#issuecomment-320333120 I will need your help to generate and encrypt an API token for codacy.  You could post the encrypted token as a comment in this PR, then I will amend my commit.  You could also try to run these commands on the command line first to see if it works:
```sh
pip2 install --user coverage codacy-coverage
coverage run setup.py test
coverage xml
export CODACY_PROJECT_TOKEN='the unencrypted token'
codacy-coverage -r coverage.xml
```
> travis: generate coverage report

- alot/commands/globals.py
- tests/commands/global_test.py
The bug in 1110 is that if sign_by_default is true, but no key is defined alot still tries to sign, even without a key. This results in undefined behavior, and some key is used, possibly changing the account. The right solution is to simply forbid sign_by_default without a gpg_key.
> Fix Issue 1110

- alot/commands/envelope.py
- alot/commands/globals.py
- alot/db/envelope.py
- alot/db/message.py
In python 3 email.Utils doesn't exist, in python 2.7 both do, but Utils
is deprecated.
> alot: replace email.Utils with email.utils

- setup.py
This series is some small cleanups for setup.py. Most importantly it adds the necessary metadata to tell pip not not try to install for python 3.x.
> setup.py cleanups

- NEWS
- alot/crypto.py
- alot/db/envelope.py
- alot/db/utils.py
- tests/crypto_test.py
- tests/db/utils_test.py
While working on the python-gpg transition I noticed that there were a lot of threads that notmuch was tagging signed that there was no signature verification being done for. After a bit of looking I realized that these messages were inside a multipart/mixed block, since they came from a mailing list and the mailing list was adding a signature to the bottom that way.
This series adds multipart/mixed handling to the encryption and signature handling code. I have tested the signing code locally, but I don't have any tests for the encrypted. I will get around to writing tests for these, but it seemed pretty involved generating emails with signatures/encrypted bits.
> Handle gpg signed and encrypted mail inside a multipart/mixed block

- alot/account.py
- alot/commands/envelope.py
- alot/settings/manager.py
- tests/commands/envelope_test.py
- tests/settings/manager_test.py
The problem is that `commands.envelope.SendCommand` simply passes the content
of the From-header to `settings.get_account_by_address`, without removing the realname part.
The problem was introduced in 084e37c, which silently drops the parsing of structured address strings .
So if the From-header is of the form "real name <email@address.org>", this does not match the account with
address "email@address.org" and falls back to the default account, which could be different.
I noticed this only by chance because my default provider (gmail) actually processes (and changes the sender) when given mails with foreign From-header values.
The first patch here moves this call into `get_account_by_address` itself, the second patch simplifies all calls to this method.
This might also fix #1110
> Fix issue with account selection

- alot/settings/manager.py
- docs/source/conf.py
- tests/settings/manager_test.py
There is a regression introduced by 86186a242c11fcbc501e7afc791a50187e0dd574 that causes default configurations to not be loaded if there is no notmuch config (for notmuch defaults) or not alot config (for alot defaults). This is because in the original patch the configs were not loaded in the constructor, but then were loaded outside the constructor. In the patch the logic that caused the constructor not to load the config was moved out of the constructor and prevented the calls in main from initializing to defaults.
> Load default settings even if a user config doesn't exist

- alot/defaults/alot.rc.spec
- docs/source/configuration/accounts_table
Mark all values for [account]encrypt_by_default as deprecated
> mark old options for encrypt_by_default as deprecated

- .gitignore
- alot/commands/__init__.py
- alot/commands/envelope.py
- alot/commands/globals.py
- alot/commands/thread.py
- alot/commands/utils.py
- alot/crypto.py
- alot/db/utils.py
- alot/errors.py
- alot/helper.py
- alot/settings/manager.py
- alot/settings/utils.py
- alot/ui.py
- alot/utils/configobj.py
- alot/widgets/globals.py
- alot/widgets/thread.py
Here's some additional py3k readying patches that do some more user/performance transparent changes in addition to those that lucc sent. These are mostly just syntactic or moved/renamed interface changes. The only thing that is significant, is the addition of the `__hash__` protocol to `TagWidget`. When implementing the `__eq__` protocol in python 2.x `__hash__` isn't required, but it is in python 3. After implementing it I noticed that the search buffer was much slower than it was before, so the hash is cached and not calculated on each walk, which makes it as fast as it was before. It's possible that we either need to make do some of the calculation asynchronously or cache them to make the interface a little faster.
> py3k small fixes

- alot/commands/globals.py
- alot/completion.py
- alot/db/manager.py
- alot/db/thread.py
This just replaces some code that only works with py2 with a variant that works both with py2 and py3.  It should not break anything but at the same time will help us on the way to py3 (also if we drop py2 later).  With these changes 79 tests can already be run with py3 and 42 pass (many still fail because of string and unicode stuff or can not even be run because of import errors).
Triggered by #1116.
If you like this PR I also have some commits which add compatible imports with a `try: import py2stuff; except ImportError: import py3stuff` pattern.  Should I add them here. (They are different in that they have to be touched again if we drop py2. These changes here don't have to be touched again.)
> Some small changes that are py2 and py3 compatible

- alot/helper.py
- tests/helper_test.py
- tests/utilities.py
Mostly this is just more tests and a little bit of test framework (the addition of an expected_failure decorator for `twisted.trial.unittest based tests`). There is one small bug fix that stops `call_cmd_async` from polluting the global environment when called.
> additional tests for the helper module

- docs/source/configuration/contacts_completion.rst
- Removed recipients search, default senders search is much faster
- Removed "my@address.org" from command, address seems to be added at the end of line automatically
> docs: `notmuch address` command updates

- alot/commands/globals.py
- tests/commands/global_test.py
Otherwise the editor will crash.
I can't figure out for the life of me to test this. I thought that I
would be able to do something like detect if stdin is a tty or something
else, but that doesn't seem to work.
Fixes #1137
> commands/globals: Only set stdin to a pipe if there is data

- docs/source/configuration/hooks.rst
This fixes the example "goodbye"-hook in order to make it work again
with v0.6 and newer branches: the initializes SettingsManager
object is now accessible as 'alot.settings.const.settings'.
> fix example hook

- alot/account.py
- alot/commands/thread.py
- alot/defaults/alot.rc.spec
- docs/source/api/settings.rst
- docs/source/configuration/accounts_table
- tests/account_test.py
- tests/commands/thread_test.py
- tests/settings/manager_test.py
Alot (like other email clients that aren't tightly coupled to one mail server) are in a difficult position, RFC 5321 section 2.3.11 (which is in the docstring of the "account: Add an Address class" patch), says that only the server for the receiving domain (for example, gmail.com) is allowed to alter or interpret the user name segment (everything before the @) in any way.
Why is this a problem for alot? Well, we need to apply the same semantics. If the server for "example.com" treats "foo@example.com" and "Foo@example.com" as equivalent (which it may), alot needs to do the same. If example.com treats them as different accounts, then alot does too.
There are simply too many servers out there to try to maintain a list of who does what (and it's a dangerous game to play, because some servers …
> Handle servers that treat the user segment of an address as case insensitive

- alot/db/message.py
The latter function returns self._id anyway, and this avoids a function
call when sorting.
I noticed this when I was looking at something else. It's a pretty minor cleanup, but it might be noticable in large threads.
> db/message: Use self._id instead of self.get_message_id()

- .github/ISSUE_TEMPLATE.md
A recent bug made me think that maybe the notmuch was out of date. It would be good to include that information in a bug report.
> github: add notmuch version to issue template

- alot/widgets/thread.py
Unless I missed something, the second call to _get_body() is not needed.
> Call _get_body() only once.

- alot/crypto.py
It seems not to be to handle error messages of different locale than en
this fixes issue #1161
> Don't use __str__ of  error BadSignature

- alot/db/manager.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
This allows to define special tags that render messages invisible.
The functionality is copied from notmuch (see man notmuch-config)
and was requested before for alot (#732).
> relay "exclude_tags" in queries

- docs/source/installation.rst
This version of GPGME is needed to support the ':sign' and ':encrypt'
commands, due to the migration of gpgme instead of pygpgme (#1086).
https://github.com/pazz/alot/issues/1175
> Upgrade dependencies to GPGME >= 1.9.0

- alot/addressbook/__init__.py
- alot/completion.py
- alot/settings/manager.py
- tests/addressbook/init_test.py
- tests/completion_test.py
- tests/settings/manager_test.py
Fixes the following crash if you have a tag that starts with `[`:
`:search tag:[<tab>`
```
Traceback (most recent call last):
File "/usr/bin/alot", line 11, in <module>
load_entry_point('alot==0.7.0.dev0', 'console_scripts', 'alot')()
File "/usr/lib/python2.7/site-packages/alot/__main__.py", line 130, in main
UI(dbman, cmdstring)
File "/usr/lib/python2.7/site-packages/alot/ui.py", line 124, in __init__
self.mainloop.run()
File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
self._run()
File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
self.event_loop.run()
File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 1200, in wrapper
rval = f(*args,**kargs)
File "/usr/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in …
```
> Tag completion: escape RE characters in search pattern.

- alot/buffers.py
.. when getting thread message count to build search buffers.
We already had a try/except block for this. This commit just moves the
one offending line into that block.
Fixes #1074
> catch exception about malformed query strings

- alot/__main__.py
- alot/account.py
- alot/commands/globals.py
- alot/settings/manager.py
- alot/settings/theme.py
- alot/settings/utils.py
- tests/commands/envelope_test.py
- tests/settings/manager_test.py
As an inexperienced user, I do a lot of silly things that leave me wonder why something doesn't work. I'm really impressed at how detailed alot can log, but at the same time I find it sometimes annoying that I have to check the logs to find out why something didn't work - which means, worst case, I have to restart alot and redo the same operation, because per default alot doesn't log anything.
So, in this particular case, I used an email address for the `from:` field that wasn't defined in the config.
In general, there are more cases where I think more information would help:
A process has ended with a probable error condition: process ended with exit code 78.`, but alot has the exact message in the logs.
So, tl;dr: if you agree these things are worth fixing, I could take a look and …
> Give better feedback on invalid user input.

- alot/__main__.py
- alot/commands/globals.py
- alot/defaults/alot.rc.spec
- alot/helper.py
- alot/settings/manager.py
- alot/ui.py
- docs/source/configuration/alotrc_table
- docs/source/configuration/theming.rst
- tests/helper_test.py
- tests/settings/manager_test.py
~~Matches the [code](https://github.com/pazz/alot/blob/054d2a932e7cb8d18dae258750ed26fb86e650b9/alot/settings/manager.py#L104).~~
- Expands environment variables:
> Bug fixes regarding XDG_* variable expansion + adds general env expansion

- alot/ui.py
When poking around  #824 I found this bug:
- alot -l log -d debug
- :search ö<enter>
- quit alot
In the log file:
```
ERROR:ui:Traceback (most recent call last):
File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 653, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/alot-0.7.0.dev0-py2.7.egg/alot/ui.py", line 679, in call_apply
return defer.maybeDeferred(cmd.apply, self)
File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 150, in maybeDeferred
result = f(*args, **kw)
File "/home/kelvin/tmp/alot/venv/lib/python2.7/site-packages/Twisted-17.9.0-py2.7-l …
```
> [WIP] Fix writing/loading history, if a command contains non-ascii character(s)

- alot/db/message.py
- alot/db/utils.py
- alot/widgets/thread.py
This fixes issue #987 and is intended as a replacement for #1163.
> mention unrendered HTML parts directly in message body text.

- alot/ui.py
This fixes two crashes I encountered when playing around with `LANG=C alot` in #673, but @pazz couldn't reproduce it. As requested, I post the one-line change here, but if no one can reproduce it I'm not sure it's worth it :-)
Reproduction steps:
- Set a custom binding in your config file. E.g.:
[bindings]
S = toggletags spam
- start alot with LANG=C: LANG=C alot
- variant A: type ö
- variant B: type :search ö
Problem: ConfigObj reads the custom binding as a unicode string, but ö is
passed as a binary string. The interaction of both leads to crashes.
Related to #673
Edit: backtrace from variant A (LANG=C alot, type ö) from #673:
```
LANG=C alot -l log -d debug
Traceback (most recent call last):
File "/home/kelvin/tmp/alot/venv/bin/alot", line 11, in <module> …
```
> Fix `LANG=C alot` with custom bindings.

- alot/commands/globals.py
- tests/commands/global_test.py
Fixes #1198 for me.
Two questions:
- Is it okay to just assume that files on Linux are encoded as 'utf-8', or should we guess the encoding (either by reading the file, or by following the hints given by environment variables)?
- The template string is passed to [parse_template](https://github.com/pazz/alot/blob/d03cd3f582818651157aa9588e5723cdaa81dc3e/alot/db/envelope.py#L281) which seems to require byte strings, such that headers like "Subject: =?iso-8859-1?q?p=F6stal?=" can be decoded later. But I don't think anyone would use a template file like that, such that it should be okay to decode the file when it's opened.
> Fix templates with non-ascii characters.

- .travis.yml
This is designed to *not break* even though we do not yet support py3.  One can mark travis jobs as "allowed failures".   As such it can be merged right now even before any actual porting to py3 has happend.
With this we can track the move to py3 on travis and it hopefully helps with #1055.
> Run tests with python3 on travis

- setup.py
Otherwise the tests will not be run with py3 on travis.  With this we can hopefully see which tests pass with #1055.  Currently the tests abort with a warning about this version requirement.
All other updates to the setup and travis file can come after #1055.
> Lift version requirement to run tests on travis (prep for #1055)

- alot/widgets/globals.py
The code currently uses "cursor up", which seems wrong to me. This
corrects searching through prompt history only moving in one direction.
Fixes #1216
> CompleteEdit: go up when the up key is pressed

- alot/account.py
- alot/commands/envelope.py
- alot/commands/thread.py
- alot/db/envelope.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/accounts_table
These patches are meant to help the sync from  tags to maildir flags to IMAP flags for the states "replied" and "passed": make alot set those tags so that notmuch updates the maildir flags accordingly and IMAP sync software can pick them up from there.
I do think they make good defaults (just like "sent"); backwards-compatibility would require an empty tag list, though.
> Tag replied passed

- alot/crypto.py
One case of this would be not having the public key of the signer. If
the verification of the signatures fails, then use the signatures from
the error, and try to redecrypt without verification.
I have no tests yet, and this probably deserves tests.
Fixes #1157
> crypto: Handle message that is encrypted, but the signature is invalid

- alot/settings/manager.py
imp is deprecated in favor of importlib.
fixes #1246
> use importlib to load hooks code at startup

- alot/commands/envelope.py
- alot/commands/utils.py
Currently the encryption keys will only be updated when they are
toggled, which means that if you change a Cc or To then the keys
encrypted to might be wrong, either too many keys will be encrypted to,
or not enough, or just the wrong ones.
This patches fixes this by calling set_encrypt whenever the 'To', 'Cc',
or 'From' headers are changed by set or unset.
Fixes #1227
> envelope: Update encryption keys when CC, To, or From is changed

- alot/__main__.py
- alot/settings/manager.py
- tests/commands/envelope_test.py
- tests/settings/manager_test.py
This prevents SettingsManager from reading the config files right when it is instantiated and instead waits for the main module to call `read_[notmuch]config` with the right path.
This should prevent problems with accidentally reading the default config paths despite being told otherwise (via commandline options)
> lazy reading of config files in SettingsManager

- alot/commands/common.py
- alot/commands/search.py
- alot/commands/thread.py
- docs/source/usage/modes/search.rst
- docs/source/usage/modes/thread.rst
retagprompt in search mode allows to retag a whole thread. The new
thread mode version allows to do the same for each selected message.
> provide retagprompt command in thread mode

- alot/commands/globals.py
Otherwise it will think that it's octet-stream and won't attach the signature.  Also use file-magic to detect the encoding, because I've had problems with chardet incorrectly identifying my signatures as ISO-8859-1.
> Open signatures as binary

- alot/widgets/globals.py
This has really annoyed me for a while, the search is reversed from vim.
In alot currently up is older searches, whiles down is newer. In vim
it's reversed.
> widgets/globals: inverse search keys (up/down)

- alot/__main__.py
- docs/source/usage/cli_options.rst
The config file setting for the colour mode used not to be respected, because a default value of a command-line option overrode it. Removing the default fixes this. I also removed the default from the command-line help as the simplest solution, but it's possible to do something more informative.
> Respect colour mode set in config file

- alot/commands/globals.py
- tests/commands/global_test.py
Email.utils apparently assumes it's getting a string, and calls encode
without converting first. This can only be hit if you have a single
account configured, not with multiple accounts.
Fixes #1277
> commands/globals: Convert Address to string for email.utils

- alot/__main__.py
- alot/commands/envelope.py
- alot/commands/globals.py
- alot/commands/search.py
- alot/commands/thread.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
- docs/source/configuration/config_options.rst
- docs/source/generate_commands.py
- docs/source/usage/cli_commands.rst
- docs/source/usage/cli_options.rst
- docs/source/usage/first_steps.rst
- docs/source/usage/index.rst
- docs/source/usage/modes/bufferlist.rst
- docs/source/usage/modes/envelope.rst
- docs/source/usage/modes/global.rst
- docs/source/usage/modes/namedqueries.rst
- docs/source/usage/modes/search.rst
- docs/source/usage/modes/taglist.rst
- docs/source/usage/modes/thread.rst
Applies a bit of copyediting polish to the documentation. I think you might want to pull everything in (obviously), but the branch should be cherry-pickable.
There are more typos and things to edit, but I’ll limit myself to this for now. One question: what should be done with the inconsistent usage of focused/focussed? (This PR leaves things as they are.)
> Copyedit documentation

- .travis.yml
- NEWS
- alot/__main__.py
- alot/account.py
- alot/buffers/search.py
- alot/buffers/thread.py
- alot/commands/bufferlist.py
- alot/commands/common.py
- alot/commands/envelope.py
- alot/commands/globals.py
- alot/commands/namedqueries.py
- alot/commands/search.py
- alot/commands/taglist.py
- alot/commands/thread.py
- alot/commands/utils.py
- alot/db/manager.py
- alot/helper.py
- alot/ui.py
- docs/source/api/conf.py
- docs/source/api/interface.rst
- docs/source/conf.py
- docs/source/faq.rst
- docs/source/installation.rst
- setup.py
- tests/commands/envelope_test.py
- tests/commands/global_test.py
- tests/commands/utils_tests.py
- tests/helper_test.py
- tests/utilities.py
I got a bit of free time, and sat down to work on something I'd really wanted to work on since we started the transition to python 3, using asyncio.
I think there are some benefits for us to using asyncio instead of twisted. Asyncio is part of the language, and it gives us nice language features like `async def` and `await`. On the downside it doesn't have as many nice convenience functions as twisted does. It also removes a pretty big, heavy dependency. Twisted is pretty cool, and you can do a lot of cool stuff with it, but we're basically just using the event loop and deferreds.
This series has been lightly tested, it does pass all of the unittests, although there are some obvious holes in the coverage of our test suite :/. I'm currently dog fooding it, but if anyone sees obvious …
> Replace twisted with asyncio

- alot/db/manager.py
"async" is not an allowed name in Python 3.7.
> db/manager: Prepend underscore to method named async

- NEWS
- alot/commands/envelope.py
- alot/commands/thread.py
- alot/db/envelope.py
- alot/db/utils.py
- alot/helper.py
- tests/db/utils_test.py
- tests/helper_test.py
Python 3.3 added a new feature to the email module, policies
(https://docs.python.org/3.5/library/email.policy.html). Policy objects
allow precise control over how numerous features work when converting to
and from str or bytes. With the `email.policy.SMTP` the behavior of
email_as_bytes and email_as_string can be achieved using the builtin
`.as_string()` and `.as_bytes()` methods, without custom code or the
need to test it. Additionally these methods handle corner cases that we
don't currently handle, such as multi-part messages with different
encodings.
Fixes #1257
> helper: replace email_as_* with email builtins

- alot/commands/thread.py
For large threads (I can reproduce on threads with ~50 messages),
changing messages can become quite slow, especially if there are a
significant number of folded messages. Removing the call to refresh the
body after moving seems to fix this.
There may be side effects of this change, and it may be required in some
cases, just not all of them.
> commands/thread: Don't refresh after moving

- alot/db/utils.py
… one
Currently in db.utils.extract_body we try to add a Content-Disposition
header, regardless of whether an email already has one. This isn't
actually legal, and individual mime message may only have one C-D. The
correction is to replace the header with the modified header if it
already exists, and to add a new one only if the message doesn't have
one.
Note that I haven't actually seen a message that hits the path that
would need "add_header", only "replace_header". I have however included
it because it would be a behavioral change to not handle that case.
Fixes #1297
> Don't try to add Content-Disposition header to mime that already has one

- extra/completion/alot-completion.zsh
Currently only the recipient addresses are completed.  It does not make
sense to add the same completion for the sender option as this should
only be used with addresses that are defined in the alot config file.
I have this code ready which we can put in a zsh function to complete the
sender account addresses.
```python
import configobj, sys
config = configobj.ConfigObj(infile=sys.argv[1], encoding="UTF8")
accounts = config.get("accounts", {})
addresses = [accounts[k].get('address') for k in accounts
if type(accounts[k]) is configobj.Section]
print(" ".join(addresses))
```
It can be defined inline in the zsh function like this:
```zsh
_alot_account_emails()
{
python3 - ${XDG_CONFIG_HOME:-~/.config}/alot/config <<-'EOF'
...
EOF
}
```
My problem currently is that I don't know enough zsh …
> Enable zsh completion of email addresses

- .travis.yml
- NEWS
- alot/__main__.py
- alot/ui.py
- setup.py
It turns out that urwid just doesn't work very will with asyncio. I simply don't have time or motivation to try to fix urwid, so instead I'm proposing trying to get the nice syntax of asyncio, but without the overhead by continuing to use urwid's `TwistedEventLoop`. Since we've installed the twisted reactor as the asyncio loop, starting Twisted's loop starts processing asyncio calls.
> Fix async idle

- alot/crypto.py
- alot/db/message.py
- alot/db/utils.py
- setup.py
- tests/db/message_test.py
notmuch caches the OpenPGP session keys if configured to do so. See
index.decrypt on:
https://notmuchmail.org/manpages/notmuch-config-1/
Using the cached session key decryption of messages can be done without
the need of having the private OpenPGP key. There is some speed up on
decryption, mostly notable on long encrypted threads.
---
This depends on a feature that hasn't being released yet:
https://git.notmuchmail.org/git?p=notmuch;a=commit;h=5e05f00fe59d2f2d7dceadefaab30bcc12b0e8df
Not sure how is this normally handled here. Should we wait for the release to merge it? Should we do a pull-req to develop or another branch? Do we need to wait certain time after the release of the feature on notmuch? Do you prefer me to close it now and open it once the time is right?
> crypto: Use session-key to decrypt messages if present in the index

- alot/account.py
- tests/account_test.py
I took the simple route, so maybe there is a better way to get the exception for the failing command than the simple assert. But this should fix #1303 which was quite annoying.
> Check the return code from sendmail

- alot/crypto.py
When the key is known or just the signature is invalid gpgme raises
'BadSignatures'. Up to now we were not acknoledging it when using
session-keys, making impossible to open emails without the signing key.
> crypto: deal with bad signatures on session-decrypt

- alot/commands/envelope.py
Bounce correctly determines the address and account to send the bounce
from. It uses the account to choose an address book for "to:" completion
and passes the sender address as "Resent-From:" to SendCommand(). The
latter uses the "From:" header, though, to determine the sending account
again and (in the case of a bounce) wrongly.
Make SendCommand() use "Resent-From:" if present and "From:" else.
Code remark: specifying "False" as the default return value for get()
ist not necessary; it is meant to make this short form clearer to read,
and to safeguard for times when '' or None do not evaluate to False
here.
Fixes #1331 :)
> make bounce command use the correct sender account

- .travis.yml
> It's suggested by the standard to use for automated messages
> And it easily avoids cycles if every bot uses notices
> i.e. only listens to privmsgs and only emits notices
> Travis: "use notices instead of regular messages"

- alot/settings/manager.py
- tests/settings/manager_test.py
As mentioned in documentation (as I recall),
but wasn't working for some time.
Makes it possible to do things like:
```
[tags]
[[lists/.*]]
translation = 'lists/(.*)', 'ʟ\1'
```
To replace lists/foo with ʟfoo (or whatever) :).
> restore support for regex in section names

- tests/db/utils_test.py
- tests/static/mail/utf8.eml
Mentioned in #1291 (sorry it took me so long).
This is just one simple test. We might need to add some more basic test for 8bit or utf8 or so before we can finally fix this.
Maybe the test case can also be formulated without an external file, I did not try that yet.
> Add test case for new encoding problems

- alot/db/message.py
Some email clients (like thunderbird) if you attach a .gpg file it will
say the attachment content type is 'application/pgp-encrypted'. We need
to discard only the attachments with content type
'application/pgp-encrypted' if they are followed by an
'application/octet-stream', beacuse this case is a PGP/MIME message:
https://tools.ietf.org/html/rfc3156#section-6.1
> db/message: accept attachments of type pgp-encrypted

- alot/db/utils.py
- tests/db/test_utils.py
176cffcd ("refactor alot.db.utils.remove_cte", 2018-12-04) created a few
problems with 8bit quoted-printable e-mails, see #1291 #1360.
This commit restores the old libmagic fallback which did not cause this
problem.
(Maybe just goood as a 0.8 hotfix.)
> restore lenient libmagic decoding

- alot/commands/thread.py
- docs/source/configuration/hooks.rst
This exposes the message object in the `reply_prefix` and `forward_prefix` hooks; now, you can mimic what Gmail does like so:
```python
def forward_prefix(*args, **kwargs):
subject = alot.db.utils.decode_header(kwargs["message"].get("Subject", ""))
to = alot.db.utils.decode_header(kwargs["message"].get("To", ""))
return (" ---------- Forwarded message ---------\n"
" From: {0} <{1}>\n"
" Date: {2:%a, %-d %b %Y at %H:%M}\n"
" Subject: {3}\n"
" To: {4}\n\n\n"
).format(*args, subject, to)
```
> expose message object to reply/forward_prefix hook

- alot/widgets/search.py
Hotfix for double width characters causing columns misalign in search
view (closes https://github.com/pazz/alot/issues/1393)
> Fix double width characters in search view

- alot/helper.py
Depending on the libmagic/ctypes version, magic_version is a function or
a constant. So far, the code expected a constant and fails on the
function variant with a TypeError.
Test with callable() und use the magic_version attribute accordingly.
> adjust to variable python-magic API

- alot/account.py
In addition, remove hardcoded default values from account.py and use defaults from alot.rc.spec
This has multiple consequences:
- default values for `sent_tags` and `draft_tags` are solely set in alot.rc.spec
- options `sent_tags` and `draft_tags` in user config do overwrite these defaults. It is now possible to not tag sent mails and drafts at all with `sent_tags = ` and `draft_tags = `
- this is a breaking change if these options were used (though a very small one). To keep the old behaviour, the user has to add `sent` and/or `draft` manually to the options.
This fixes #1412
> Options overwrite default values for sent_tags and draft_tags

- alot/commands/search.py
- alot/widgets/thread.py
This will prevent the whole message from being read and interpreted
at the time we instantiate a MessageTree for display and instead only
create the (cheap!) summary widget.
When a user manually interacts with the Message widgets (for example by
unfolding/toggling source) then the content parts will anyway be
reassembled. The consequence of this patch is that loading large threads
should be much faster.
> Faster Thread loading

- alot/completion.py
- tests/test_completion.py
email.utils.formataddr does more encoding than we need at this point -
headers will be encoded when they get inserted anyway.
Use db.utils.formataddr instead. Fixes #1378
> ContactsCompletion: use db.utils.formataddr

- alot/commands/thread.py
- alot/db/message.py
- alot/db/utils.py
- alot/widgets/search.py
- alot/widgets/thread.py
- docs/source/usage/modes/thread.rst
- tests/db/test_utils.py
This is a continuation of #1348
> 0.8 get body

- .travis.yml
- setup.py
- tests/addressbook/test_external.py
- tests/commands/test_envelope.py
- tests/commands/test_global.py
- tests/commands/test_init.py
- tests/commands/test_thread.py
- tests/commands/utils_tests.py
- tests/db/test_envelope.py
- tests/db/test_message.py
- tests/db/test_thread.py
- tests/db/test_utils.py
- tests/settings/test_manager.py
- tests/settings/test_utils.py
- tests/test_completion.py
- tests/test_crypto.py
- tests/test_helper.py
- tests/utilities.py
- tests/utils/test_argparse.py
- tests/widgets/test_globals.py
It was added to the stdlib in py3.3 and we already require 3.5.
I am trying to write a test for #1303 and found this on the way.
> Use unittest.mock from the stdlib

- alot/db/utils.py
- tests/db/test_utils.py
Make HTML-only mails display again.
(No, they'll never be "great".)
> Fix html only mails

- alot/commands/globals.py
- tests/commands/test_global.py
Implements the suggestion in #1427 to display the actual error code, and
substitutes an empty stderr with "No stderr output".
I figured, while I'm rooting around in that file, might as well implement that
<15mins suggestion.
> Be more informative if editor exits with error.

- alot/commands/globals.py
Bypasses the handling of editor_cmdstring if this is not set after all
attempts, which will eventually lead to EditCommand.apply erroring
with 'no editor set' instead of alot crashing.
Fixes #1438
> Check whether editor_cmdstring is set before searching it.

- docs/source/installation.rst
- setup.py
Hey,
Following the issue #1420 I have bump twisted to be at least 18.4.0,
this patch need some checking to be sure everyone can have this version.
> Bump twisted to >= 18.4.0 fix #1420

- alot/account.py
- alot/buffers/thread.py
- alot/commands/envelope.py
- alot/commands/globals.py
- alot/commands/search.py
- alot/commands/thread.py
- alot/db/envelope.py
- alot/db/utils.py
- alot/helper.py
- alot/settings/manager.py
- alot/ui.py
- alot/widgets/globals.py
- docs/source/api/conf.py
- docs/source/conf.py
- tests/addressbook/test_external.py
- tests/commands/test_envelope.py
- tests/commands/test_global.py
- tests/commands/test_init.py
- tests/commands/test_thread.py
- tests/db/test_envelope.py
- tests/db/test_message.py
- tests/db/test_utils.py
- tests/settings/test_manager.py
- tests/test_account.py
- tests/test_crypto.py
- tests/test_helper.py
- tests/utilities.py
- tests/widgets/test_globals.py
In order to confuse new developers less.
> Remove unicode literals syntax from python2

- .travis.yml
- tests/utilities.py
The error handling code needs tearDown_exceptions in the new version of Python. Otherwise the following error appears:
```
Traceback (most recent call last):
File "setup.py", line 7, in <module>
setup(
File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
dist.run_commands()
File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 229, in run
self.run_tests()
File "/usr/lib/python3.8/site-packages/setuptools/command/test.py", line 247, in run_tests
test = unittest.main( …
```
> Fix compatibility with Python 3.8

- alot/buffers/envelope.py
- alot/widgets/thread.py
this simply calls helper.string_sanitize on the (real) email "body" text
before handing it to the urwid Text widget.
The original message may contain tabs, which are untouched when sending
the message. The sanitization is only for displaying this string, and
should replace tabs by whitespaces as expected.
fix #1439
> sanitize message body text for display in envelope

- alot/commands/envelope.py
- alot/utils/collections.py
This should mitigate issue #898 by keeping the order of editable headers from either the configuration or the current envelope.
__This change set hasn't been tested.__
> commands/envelope: keep editable headers order

- alot/db/envelope.py
- tests/db/test_envelope.py
Fixes an issue introduced in 45829f7956716638fe77989a50eb87d3ea34cace
which made header values containing ':' break the parser.
> envelope: fix header key:value parsing regression

- alot/db/envelope.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
This allows users to use a custom domain in automatically generated
Message-ID headers instead of the local hostname.
> envelope: add setting for custom Message-ID domain

- alot/buffers/envelope.py
- alot/commands/envelope.py
- alot/commands/thread.py
- alot/db/envelope.py
- alot/defaults/alot.rc.spec
- alot/errors.py
- docs/source/configuration/alotrc_table
- docs/source/usage/modes/envelope.rst
- tests/commands/test_global.py
- tests/db/test_envelope.py
as discussed in #1051.
This will use a new config string "txt2html_converter" to translate plaintext body message to html and change the created mime structure accordingly.
See https://stackoverflow.com/questions/10631856/mime-type-to-satisfy-html-email-images-and-plain-text
It works nicely for me when I compose simple markdown and use "pandoc -t html" as converter.
But I expect it to get messy with reply quotes (untested for now).
> Call a text-to-html converter to build html alternative body parts

- alot/defaults/alot.rc.spec
- alot/widgets/ansi.py
- alot/widgets/thread.py
- docs/source/configuration/alotrc_table
This is a rebase of an old branch "0.3.6-feature-color-wip", which I will retire now, and ultimately passes on a proof-of-concept implementation of TextWidgets that interprets [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors).
The aim is to let the html renderer interpret colours from html mails and translate them to ANSI escapes. For instance, elinks can do this:
```
text/html; elinks -force-html -dump -dump-color-mode 3 -dump-charset utf8 -eval 'set document.codepage.assume = "%{charset}"' %s; copiousoutput
```
This feature can be enabled simply by configuring your mailcap as above and should not have any effect
if the browser does not produce these characters.
The boolean config setting can be used to disable interpretation of a subset of escape codes,
those …
> [RFC] ANSI-escape codes for colourful HTML mails

- alot/commands/__init__.py
- alot/commands/globals.py
- alot/ui.py
- docs/source/usage/modes/global.rst
First attempt at implementing a confirmation command intended for use in
command sequences, as discussed in #1368.
When called (optionally with a free-form string message), prompts the
user for confirmation. If the user declines, a SequenceCanceled
exception is raised, which trickles up the error handling into
apply_commandline where it is explicitly caught outside the common error
handler. This aborts the execution of subsequent commands in the
commandline, but does not show up as an error in the log.
Closes #1368
> Implement command for confirming command sequences.

- alot/db/utils.py
Fixes the missing HTML message, displayed when an HTML body can't be
rendered because there is no functional mailcap entry. The message
refers to the online FAQ, but the item was the wrong one.
> Fix the missing HTML message

- alot/db/utils.py
- tests/db/test_utils.py
My use case is limiting width:
text/plain; fmt -w 80 -s %s
> Allow optional text/plain mailcap entry.

- alot/commands/envelope.py
- alot/widgets/ansi.py
```
alot/alot/widgets/ansi.py:84: SyntaxWarning: "is" with a literal. Did you mean "=="?
if code is 0:
alot/alot/commands/envelope.py:762: SyntaxWarning: "is" with a literal. Did you mean "=="?
if self.action is "txt2html":
alot/alot/commands/envelope.py:768: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif self.action is "html2txt":
```
Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955193
Signed-off-by: Jordan Justen <jordan.l.justen@intel.com>
> Fix 'SyntaxWarning: "is" with a literal.' from Python 3.8

- alot/commands/envelope.py
- docs/source/usage/modes/envelope.rst
This renames the "unattach" command to "detach" and makes it accept a glob
pattern for consistency with "attach".
GitHub: closes #1489
> commands: envelope: better attachment removal

- alot/buffers/thread.py
- alot/commands/thread.py
- alot/completion/command.py
- alot/db/message.py
- alot/db/utils.py
- alot/defaults/alot.rc.spec
- alot/defaults/default.bindings
- alot/widgets/ansi.py
- alot/widgets/thread.py
- docs/source/configuration/alotrc_table
- docs/source/usage/modes/thread.rst
- tests/db/test_utils.py
This supersedes #1475 in response to the review there.
> Take 3: Mimetree and mime part support. Resolve #862.

- alot/ui.py
If the terminal previously did show another curses application (e.g.
VIM) that content might be shown upon starting alot until the first
command has been executed and the result printed. By simply clearing the
screen before entering the mainloop we can work around that.
> Clear the screen before initial paint

- alot/commands/envelope.py
- alot/db/envelope.py
- tests/db/test_envelope.py
`default` policy ensure headers are correctly encoded (i.e. will not
leak non-ascii char in headers)
(related to #1482)
> envelope: set policy when constructing email

- alot/buffers/search.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
This commit allows keeping the currently focused message selected
across thread refreshes.
Since this operation can take a long time in large threads, a
`search_threads_rebuild_limit` option is introduced. When defined,
it sets the maximum amount of messages that will be iterated upon
when trying to find the previously focused message.
> Don't lose the focus when refreshing a thread

- alot/helper.py
- tests/test_helper.py
Fixes https://github.com/pazz/alot/issues/1454:
Can't attach a file if filename contains a semicolon
> ignore quoted separators when splitting command lines

- alot/db/utils.py
- tests/db/test_utils.py
- tests/static/mail/basic.eml
`get_params()` returns `None` when the header is missing. Use `failobj` argument to mitigate that.
Fixes #1512
> Fix mailcap rendering for e-mails without `Content-Type` header

- alot/db/utils.py
- tests/db/test_utils.py
This seems to essentially revert 777823f414aab5dfa130174dc7c80cda8036d13f,
the reasoning of which I don't yet follow.
This may resolve the issue in #1522.
> Fix utf8 encoding with a text/plain mailcap entry.

- alot/buffers/thread.py
So `thread.py` was using `self.body.set_focus` 'directly' in various places. Changing all references to use `self.set_focus` as a wrapper ensures every call uses `valign='top'` and it focuses as expected for the other commands (`move next`, `move next|previous sibling` etc).
There's a minor annoyance remaining in that align-to-top doesn't happen for the last message(s) if their total length is less than the window height. The fix I suspect would be to add some padding to the end somehow, but this is probably a separate issue/feature.
> Focus valign part 2 (#1528 continued)

- alot/buffers/search.py
After rebuilding the threadlist, we still need to actually update the focused thread. Currently, in a buffer with more than 200 results you need to run the command twice to actually change the selected thread.
Would you accept a PR to make this limit of 200 results configurable? I personally find it annoying that the ordering of the threads is incorrect because of this, at least according to the original order, as `oldest-first` is not the reverse of `newest-first`. I currently use `move last; refresh` as a best-effort workaround.
> fix move first and last

- alot/db/manager.py
Since the move to notmuch2, tag changes were no longer synchronised to Maildir flags.
> fix synchronisation of tags to Maildir flags

- alot/buffers/search.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
As discussed in #1561, I added an option to configure the maximum number of results before using the reverse order heuristic for `move last`. I kept the default at `200`, although `search_threads_rebuild_limit` is unlimited by default, as we do have the heuristic approach as a fallback.
I also disabled restoring focus after the building the reversed threadlist, as that is limited by `search_threads_rebuild_limit`, making this heuristic pointless by default, as you still load the whole threadbuffer, while getting an inexact order. And even when `search_threads_rebuild_limit` is set to a different value, it would still be unnecessarily slow.
> configurable limit on move last

- alot/commands/thread.py
Explicitly expand or collapse every message, like we do in `ThreadBuffer.unfold_matching` instead of only expanding or collapsing the matching messages.
Closes #1496
> fix fold and unfold commands

- alot/commands/thread.py
- alot/db/manager.py
There still seems to be quite a fall-out from the conversion of alot to nm2. This PR so far only solves one related to the toggletags command and the question whether toggle is per message or per thread (best described in the commit messages).
I have other weird effects, such as `notmuch search` giving a thread with 16 messages and `alot search` giving me only 1 message for that thread, and so does the thread buffer. I have not tracked this down yet.
This PR might serve to collect more fixes or be merged directly if deemed correct. Am I the only one experiencing these issues? I don't see any related bug reports.
> Fix toggletags

- alot/buffers/search.py
- alot/db/manager.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
This changes alot's exclude tag setting to use the notmuch exclude_tags setting as a fallback when the alot setting isn't set, as discussed in #1566.
> use notmuch exclude_tags as fallback

- alot/db/thread.py
The notmuch2 bindings change now means the retrieval of the oldest
subject from a thread needs to be reworked.
When the config option is chosen to use the oldest subject:
```
thread_subject = oldest
```
The following error is generated:
```
File "/home/kbingham/iob/alot/alot/db/thread.py", line 50, in _refresh
first_msg = list(thread.get_toplevel_messages())[0]
AttributeError: 'Thread' object has no attribute 'get_toplevel_messages'
```
Update the code to use the correct interface on both the Thread and
Message objects.
> db: thread: Fix 'oldest subject' thread names

- alot/__main__.py
- alot/helper.py
- docs/source/api/settings.rst
- docs/source/usage/cli_options.rst
Since a while ago notmuch allows to notmuch config file to be stored in some new locations (XDG directories).  This PR adds support for the new locations and env variables.  The official docs are in https://notmuchmail.org/manpages/notmuch-config-1/
I simplified the docs to refer to the notmuch man page because the new algorithm to find the file is unwieldy and I did not wat to copy it. I hope that is ok.
> Find notmuch config in new locations

- docs/source/faq.rst
- docs/source/installation.rst
Apparently this w3m option is not very well known, to the point where people are advised to switch to lynx.
> Suggest -o display_link_number=1 for w3m

- alot/commands/globals.py
- extra/hooks/external_command_tmux_without_x11.py
- extra/tmux-horizontal-split-blocking.sh
I spent entirely too long today fixing my own instance of #1560, because I'm not running alot in X11 and #460 and 2a7d1fd2dcc7354b06faa0da5574324b3578eba1 make alot simply fall back to non-spawning behaviour silently.
Initially I special-cased tmux outside of X11 in alot/commands/globals.py, but then I found out that I'm supposed to write a hook. So I did that, but I'd like to document it publicly.
There's also a bug where the `thread` result of that hook is not respected because `self.in_thread` gets set directly.
- Ensure the `thread` result of the `touch_external_command` hook is not overridden.
- Provide an example `touch_external_command` hook and corresponding shell script for tmux outside of X11. (Thanks to @cjpbirkbeck in …
> Fix external tmux command without display

- alot/commands/search.py
This is specially necessary if one is chaining a series of tagging commands.
As an example, without this fix, in the chain "untag inbox,unread --no-flush; tag foo,bar", the second command would not work properly if the current search buffer's query string was "tag:inbox and tag:unread".
> commands/search/tag: Use only thread id in testquery

- alot/db/thread.py
> Catch LookupError if message has no Subject header

- alot/commands/thread.py
- alot/utils/ansi.py
- alot/widgets/ansi.py
When replying to an email containing ANSI CSI escapes, those sequences are currently included in the reply's quoted message. This PR makes sure they are removed. While working on it, I realized some other issues in the generation of urwid attributes and added fixes for those as well.
> Fix some issues regarding ANSI CSI handling

- alot/db/manager.py
- alot/defaults/notmuch.rc
- alot/defaults/notmuch.rc.spec
- alot/settings/manager.py
- alot/settings/utils.py
- setup.py
The main benefit from this is that we get the defaults directly from
notmuch and do not risk using inconsistent configuration values.
A good example of this is getting the database path. Getting the path
directly from the notmuch config file is not enough, because the user
might be using the default location with no explicit entry in the file.
Since notmuch does is a bit of logic notmuch to get the database path
(see section "DATABASE LOCATION" in man page for notmuch-config(1)), it
is better to get it directly from "notmuch config".
Since get_notmuch_setting() now always returns a string, also refactor
the call to settings.get_notmuch_setting('maildir', 'synchronize_flags')
for this new reality.
> alot/settings: Use notmuch config to read configuration

- flake.lock
- flake.nix
when I packaged alot for poetry, I did it within a ubuntu container and I realized it was not that easy to setup (I've updated instructions in the doc in that same PR). Nix is a package manager aiming at reproducibility and it excels in it.
With nix installed one can run `nix run 'github:teto/alot/flake'` to test the PR (though it is currently failing).
Likewise  `nix develop 'github:teto/alot/flake'` will give you a development environment with all dependencies available.
Note: this is easy to maintain out of tree. The 2 flake.* files can be moved in a contrib/ folder to not crowd the root directory.
> add a nix flake

- alot/defaults/alot.rc.spec
- alot/utils/configobj.py
- docs/source/configuration/accounts.rst
- docs/source/configuration/accounts_table
Hey! 
I noticed that environment variable expansion did not work with `draft_box`. This patch will add that, and for `sent_box` too. (Implemented it in `mail_container`). The change itself is just 1 line, the rest is documentation.
I'd use this to have the same configuration on macOS and Linux, because my mail directory is in different places on these systems. 
Any feedback is of course welcome!
> Support env variables in mail_container path

- alot/commands/globals.py
This issue is referenced here: https://github.com/pazz/alot/issues/1318#issuecomment-629711726
> ExternalCommand: Fix unbound variables.

- alot/utils/configobj.py
- tests/utils/test_configobj.py
Some current config tuple checking is of the form:
```python
if not isinstance(value[1], int) or not isinstance(value[2], int):
VdtTypeError(value)
```
This has two problems. The first is that `isinstance('123', int)` is always `False`, which means the if's block always runs. A `VdtTypeError` would always be raised except that the `raise` keyword is missing.
This PR attempts to fix that issue.
> Fix configobj to relay tuple type errors

- alot/defaults/default.theme
> make default theme readable

- alot/defaults/alot.rc.spec
Hey!
A very small patch that makes the default value for the hooks file use `$XDG_CONFIG_HOME` instead of `~/.config`. The previous behaviour was non-conforming.
I did not update the documentation because of two reasons:
* The documentation is currently inconsistent in calling out env variable support. so adding it should probably be in a different commit.
* the table in `docs/source/api/settings.rst` would get a bit wider and thus unreadable in my editor.
> Fix default hooks config path to conform to XDG

- alot/ui.py
If e.g. two SIGUSR1 signals arrive at almost the same time, it can be that the first one hasn't finished refreshing the UI yet when the second one needs to be handled, leading to a generator being executed twice, which python doesn't like.
We try to avoid this by scheduling the actual handling logic as a coroutine on the currently running event loop.
This has the advantage that the signal handler now has full access to any async functions or synchronization primitives.
As long as the event loop is single-threaded, the current version should avoid this particular crash as the refreshing logic is not async and hence cannot be interrupted at the event loop level.
If this were to change at some point, an asyncio.Semaphore or equivalent primitive can be easily introduced.
> Avoid signal handling reentrancy issues

- .github/workflows/check.yml
- .github/workflows/test.yml
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update github actions to run on node 20

- alot/__main__.py
According to POSIX, a program which has not called `setlocale(LC_ALL, '')` runs using the portable 'C' locale. Calling `setlocale(LC_ALL, '')` lets it use the default locale as defined by the LANG variable.
Source: https://docs.python.org/3/library/locale.html#locale.getdefaultlocale
Applications typically start with a call of
```python
import locale
locale.setlocale(locale.LC_ALL, '')
```
Source: https://docs.python.org/3/library/locale.html#locale.setlocale
Setting the locale fixes the detection of 24h format.
`pretty_datetime` function checks if `time.strftime("%p")` is empty for branching between 12h / 24h:
https://github.com/pazz/alot/blob/3a3fc88deaaf134c3f2b583ca852f37afbf447e5/alot/helper.py#L216-L217
According to the documentation above, the locale falls back to C and the format …
> Set the locale to the user’s default setting

- .github/workflows/check.yml
- .github/workflows/test.yml
- .github/workflows/test.yml-broken
- alot/db/manager.py
- alot/helper.py
- alot/settings/utils.py
- flake.nix
- pyproject.toml
- tests/db/test_manager.py
- tests/db/test_utils.py
- tests/test_helper.py
This adds CI jobs to run the nix build of alot and also a second nix target with a ci job to build the sphinx docs.
Some test are fixed or removed, see commit messages.  The last question about the fixed test is https://github.com/pazz/alot/pull/1653#issuecomment-2094563736
The plan behind this is that we have *some* CI that is green until the pip/poetry installation of alot is fixed again and our other CI jobs can be trusted.  And also to check that the nix code works correctly because I personally rely on it.
> Add github action to check the nix build

- README.md
The badge did still point to travis which is not used any longer.  The new batch points to our github actions and shows the status of the action in the check.yml file.
It looks like this: https://github.com/pazz/alot/tree/readme-badge?tab=readme-ov-file
Sadly the text can not be controlled on the badge but is copied from the workflow file's `name` field.
> Update ci badge in the readme

- alot/helper.py
This fixes: #1608
This workaround was introduced in 2013: d093628919b35ee5dda77ca1e4f4e4f951259fd3
Since then the libmagic bug was fixed, additionally it should have been propagated through all release channels of all major distros.
> removed obsolete/faulty libmagic workaround

- alot/db/thread.py
- alot/helper.py
- tests/test_helper.py
I recently noticed that some messages (primarily spam) contain [control characters](https://www.compart.com/en/unicode/category/Cc) that result in garbled output in both the search widget and the thread view. This PR addresses this by
1. removing all unwanted control characters (and not just CR) from strings before outputting and
2. applying string_sanitize() to subjects in the search widget.
> Properly sanitize control chars in subject/headers/body

- alot/commands/search.py
- alot/defaults/alot.rc.spec
When defined this option will make only matching messages unfold when opening a thread. Saves time rendering, avoids hacks like `select; fold *; ...` and improves ui/ux.
Sample use:
`thread_unfold_matching = "tag:unread"`
> Added an option to unfold only messages matching a query

- alot/commands/thread.py
When forwarding a mail, the outgoing mail, and any follow up
conversation becomes a disjointed thread.  This removes the original
context, and makes it harder to find and track while the conversation
splits in two directions.
Add appropriate reference headers to the envelope when constructing a
forwarded mail to ensure that the conversations continue to be related
and therefore presented in the same thread with notmuch and alot.
Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>
> commands: thread: Reference existing message when forwarding

- flake.nix
This makes our  nix derivation usable not only as a development environment but also for installation in a nix based system and daily use. 
(I am installig the current master of alot on my home computer through this way and would like to have these goodies)
> nix: install support files

- flake.nix
@pazz this is the result of my comment https://github.com/pazz/alot/issues/1666#issuecomment-2270396622 . This makes the nix code a little more complicated but removes the need to specify our dependencies twice.  As I know nix quite well I like it but I am unsure if it raises the bar for others to look at the nix code (do we care about that?). What do you think?
> nix: parse dependencies from pyproject file

- .github/workflows/test.yml-broken
- flake.nix
- tests/commands/test_global.py
We are running our tests in different environments, sometimes with a terminal as stdin and sometimes with /dev/null as stdin.  Both are seen as "not a pipe" by `test -p` so we use that to test if our python code redirects text into an external process.
This fixes #1580.
This pull request is based on my comment https://github.com/pazz/alot/issues/1580#issuecomment-2258138340
> Fix spawn tests in different environments

- alot/defaults/alot.rc.spec
- alot/settings/manager.py
- docs/source/configuration/alotrc_table
- docs/source/configuration/hooks.rst
This changes the default setting of the 'hooksfile' setting and associated behaviour so that, unless explicitly set, this config setting defaults to `None`, which then means loading the hooksfile is not even attempted.
Prior to this commit, the default value was
`$XDG_CONFIG_HOME/alot/hooks.py`
and no alot would try to read that file upon start (and report via logging.exception if it failed, which in the ui is uncritical).
This was problematic not only in that it hardcodes the unix separator '/' but also because it caused unecessary disk access / errors. More importantly, it caused several test cases to fail (see [here](https://bugs.gentoo.org/874372#c2).
The patch also includes updated docs.
> Make hooks optional

- alot/__main__.py
- alot/db/manager.py
This change causes alot to pass on the "notmuch-config" option (path to notmuch's configuration file) to any call to `Database(..)` in the underlying database.
#1597
> notmuch2 copatibility

- readthedocs.yaml
I think this should do it.
@pazz  I took the liberty to also push this branch to the "rtd" branch as that still looks activated on RTD. So I hope to get a build of this branch on RTD (maybe you can check and if neccesary activate the dversion or dversion2 branch on RTD).
> Fix build on RTD with dynamic version

- .github/workflows/check.yml
We had this check when ci was still run on travis.  The commit f1bbd00862d2b6b050c755f36262597af22bb824 indicates that such a check is currently needed.
> Add a ci check for the generated docs

- alot/db/utils.py
The `get_body(...)` call (and hence the nominal return of the `get_body_part(...)` method) returns a email.message.EmailMessage. So if there is no body return an empty such class instead of a string, because the callers expects that it behaves like a message. E.g.:
File "alot/db/utils.py", line 499, in extract_body_part
**{'field_key': 'view'} if body_part.get_content_type() == 'text/plain'
^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_content_type'
Someone sent me a message where the body was some encapsulated message. I still have not gotten it rendered properly, but showing up as an empty message is at least better than crashing alot
> Fix return type of message without a preferred body

- .git_archival.txt
- .gitattributes
The `sdist` source does not include all file relevant to Fedora packaging, particularly the `docs` folder that is used to generate the `man` pages. Therefore we need to use the git archive, but for this the `.git_archival.txt` file is missing: https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives
> Add `.git_archival.txt`

- pyproject.toml
Python 3.13 removed the dead battery mailcap and it is now offered on PyPi. This is temporarily workaround.
Related: #1632
> Support Python 3.13's removal of mailcap

- flake.nix
This should fix the nix build which is broken due to #1684.
The standard-mailcap package is not yet available in nixpkgs so this still breaks for python 3.13 on nix but at least the dependency parsing works again and the derivation can be used with python <=3.12.
---------
@pazz what do you think about requiring green CI for pull requests? I would quite like that.
> Update flake for new mailcap dependency

- alot/defaults/default.theme
e90da9b3da225683c0ab6e8890ebda916d3c4d97 broke the highlighting of focused_attachments.
This PR resets the faulty value in question to its prior color.
> fix default-theme to correctly highlight focused attachments

- flake.lock
- flake.nix
This frees us from some hand written setup code.
> nix: use pyproject-nix to parse the pyproject.toml file

- alot/buffers/search.py
- alot/commands/globals.py
- alot/commands/search.py
- alot/db/manager.py
- alot/defaults/alot.rc.spec
- docs/source/configuration/alotrc_table
- docs/source/usage/modes/global.rst
- docs/source/usage/modes/search.rst
The new search_threads_limit option can be used to configure a default maximum number of results for thread searches. The value can be overridden by using the --limit argument.
Addresses issue #1647.
> Introduce a configurable thread search limit
